title:              Gean Ramos - gean.me
email:              contato@geanramos.com
description:        A Blog Theme by Start Bootstrap
author:             Gean Ramos
baseurl:            "/"
url:                "./"

# Social Profiles
twitter_username:   geanramos
github_username:    geanramos
facebook_username:  geanramoss
instagram_username:  geanramus
linkedin_username:  geanramos

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
